image: Visual Studio 2019
configuration: Release
install:
  - choco install gitversion.portable -y
deploy:
  provider: environment
  name: nuget
  artifact: /.*\.nupkg/
  on:
    branch: main
    appveyor_repo_tag: true
before_build:
  - cmd: gitversion /l console /output buildserver /updateassemblyinfo
  - nuget restore
build:
  verbosity: minimal
  project: Sally7.sln
after_build:
  - dotnet pack Sally7 -c %CONFIGURATION% /p:Version=%GitVersion_NuGetVersion% --no-build -o artifacts
artifacts:
  - path: artifacts\*.*